#!/bin/bash
#
# Copyright 2015 Formal Methods and Tools, University of Twente
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$#" -ne 1 ]; then
    >&2 echo "usage: $0 <petri-net.pnml>"
    exit 1
fi

filename=$(basename "$1")
extension="${filename##*.}"
filename="${filename%.*}"

/usr/bin/python3 /home/jeroen/.local/bin/pnml2pins.py $1 > $filename.c
gcc -c -I/usr/local/include/ltsmin -std=c99 -fPIC -g -O2 /home/jeroen/.local/share/pnml2pins/common/pnml-pins.c $filename.c
gcc -shared -o $filename.so $filename.o pnml-pins.o
rm -f pnml-pins.o
rm -f $filename.o
